name: Automate Build and Testing Front-end

on:
  pull_request:
    branches:
      - master

defaults:
    run:
        working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14-latest
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn
      - run: yarn lint
      - run: yarn test:ci
      - run: yarn build